// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDW-g3bK9FXZqKqssKj40aGZIpfpg3mfc',
    appId: '1:644869848464:web:f609f7da3c09819a3b0715',
    messagingSenderId: '644869848464',
    projectId: 'flutter-679c6',
    authDomain: 'flutter-679c6.firebaseapp.com',
    storageBucket: 'flutter-679c6.appspot.com',
    measurementId: 'G-YL4GE0SENG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlpL7-kHOZlTlfeAbtPt7fKvWiX2AUKCU',
    appId: '1:644869848464:android:7857586535c5214c3b0715',
    messagingSenderId: '644869848464',
    projectId: 'flutter-679c6',
    storageBucket: 'flutter-679c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2B1wI_YvEoBVD_jlfYJI-el3QhE7pmA',
    appId: '1:644869848464:ios:d0e626c647ee365c3b0715',
    messagingSenderId: '644869848464',
    projectId: 'flutter-679c6',
    storageBucket: 'flutter-679c6.appspot.com',
    iosClientId: '644869848464-6n3d8n3d382ulln7advjbpks6djuaoou.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2B1wI_YvEoBVD_jlfYJI-el3QhE7pmA',
    appId: '1:644869848464:ios:d0e626c647ee365c3b0715',
    messagingSenderId: '644869848464',
    projectId: 'flutter-679c6',
    storageBucket: 'flutter-679c6.appspot.com',
    iosClientId: '644869848464-6n3d8n3d382ulln7advjbpks6djuaoou.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationDemo',
  );
}
